import java.util.Map;
import java.util.HashMap;

public class SBoxTables {
      
    public static Map<String, Map<String, String>> sBox1 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "14");
            put("1", "4");
            put("2", "13");
            put("3", "1");
            put("4", "2");
            put("5", "15");
            put("6", "11");
            put("7", "8");
            put("8", "3");
            put("9", "10");
            put("10", "6");
            put("11", "12");
            put("12", "5");
            put("13", "9");
            put("14", "0");
            put("15", "7");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "0");
            put("1", "15");
            put("2", "7");
            put("3", "4");
            put("4", "14");
            put("5", "2");
            put("6", "13");
            put("7", "1");
            put("8", "10");
            put("9", "6");
            put("10", "12");
            put("11", "11");
            put("12", "9");
            put("13", "5");
            put("14", "3");
            put("15", "8");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "4");
            put("1", "1");
            put("2", "14");
            put("3", "8");
            put("4", "13");
            put("5", "6");
            put("6", "2");
            put("7", "11");
            put("8", "15");
            put("9", "12");
            put("10", "9");
            put("11", "7");
            put("12", "3");
            put("13", "10");
            put("14", "5");
            put("15", "0");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "15");
            put("1", "12");
            put("2", "8");
            put("3", "2");
            put("4", "4");
            put("5", "9");
            put("6", "1");
            put("7", "7");
            put("8", "5");
            put("9", "11");
            put("10", "3");
            put("11", "14");
            put("12", "10");
            put("13", "0");
            put("14", "6");
            put("15", "13");
        }});
    }};
        
    public static Map<String, Map<String, String>> sBox2 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "15");
            put("1", "1");
            put("2", "8");
            put("3", "14");
            put("4", "6");
            put("5", "11");
            put("6", "3");
            put("7", "4");
            put("8", "9");
            put("9", "7");
            put("10", "2");
            put("11", "13");
            put("12", "12");
            put("13", "0");
            put("14", "5");
            put("15", "10");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "3");
            put("1", "13");
            put("2", "4");
            put("3", "7");
            put("4", "15");
            put("5", "2");
            put("6", "8");
            put("7", "14");
            put("8", "12");
            put("9", "0");
            put("10", "1");
            put("11", "10");
            put("12", "6");
            put("13", "9");
            put("14", "11");
            put("15", "5");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "0");
            put("1", "14");
            put("2", "7");
            put("3", "11");
            put("4", "10");
            put("5", "4");
            put("6", "13");
            put("7", "1");
            put("8", "5");
            put("9", "8");
            put("10", "12");
            put("11", "6");
            put("12", "9");
            put("13", "3");
            put("14", "2");
            put("15", "15");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "13");
            put("1", "8");
            put("2", "10");
            put("3", "1");
            put("4", "3");
            put("5", "15");
            put("6", "4");
            put("7", "2");
            put("8", "11");
            put("9", "6");
            put("10", "7");
            put("11", "12");
            put("12", "0");
            put("13", "5");
            put("14", "14");
            put("15", "9");
        }});
    }};

    public static Map<String, Map<String, String>> sBox3 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "10");
            put("1", "0");
            put("2", "9");
            put("3", "14");
            put("4", "6");
            put("5", "3");
            put("6", "15");
            put("7", "5");
            put("8", "1");
            put("9", "13");
            put("10", "12");
            put("11", "7");
            put("12", "11");
            put("13", "4");
            put("14", "2");
            put("15", "8");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "13");
            put("1", "7");
            put("2", "0");
            put("3", "9");
            put("4", "3");
            put("5", "4");
            put("6", "6");
            put("7", "10");
            put("8", "2");
            put("9", "8");
            put("10", "5");
            put("11", "14");
            put("12", "12");
            put("13", "11");
            put("14", "15");
            put("15", "1");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "13");
            put("1", "6");
            put("2", "4");
            put("3", "9");
            put("4", "8");
            put("5", "15");
            put("6", "3");
            put("7", "0");
            put("8", "11");
            put("9", "1");
            put("10", "2");
            put("11", "12");
            put("12", "5");
            put("13", "10");
            put("14", "14");
            put("15", "7");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "1");
            put("1", "10");
            put("2", "13");
            put("3", "0");
            put("4", "6");
            put("5", "9");
            put("6", "8");
            put("7", "7");
            put("8", "4");
            put("9", "15");
            put("10", "14");
            put("11", "3");
            put("12", "11");
            put("13", "5");
            put("14", "2");
            put("15", "12");
        }});
    }};

    public static Map<String, Map<String, String>> sBox4 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "7");
            put("1", "13");
            put("2", "14");
            put("3", "3");
            put("4", "0");
            put("5", "6");
            put("6", "9");
            put("7", "10");
            put("8", "1");
            put("9", "2");
            put("10", "8");
            put("11", "5");
            put("12", "11");
            put("13", "12");
            put("14", "4");
            put("15", "15");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "13");
            put("1", "8");
            put("2", "11");
            put("3", "5");
            put("4", "6");
            put("5", "15");
            put("6", "0");
            put("7", "3");
            put("8", "4");
            put("9", "7");
            put("10", "2");
            put("11", "12");
            put("12", "1");
            put("13", "10");
            put("14", "14");
            put("15", "9");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "10");
            put("1", "6");
            put("2", "9");
            put("3", "0");
            put("4", "12");
            put("5", "11");
            put("6", "7");
            put("7", "13");
            put("8", "15");
            put("9", "1");
            put("10", "3");
            put("11", "14");
            put("12", "5");
            put("13", "2");
            put("14", "8");
            put("15", "4");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "3");
            put("1", "15");
            put("2", "0");
            put("3", "6");
            put("4", "10");
            put("5", "1");
            put("6", "13");
            put("7", "8");
            put("8", "9");
            put("9", "4");
            put("10", "5");
            put("11", "11");
            put("12", "12");
            put("13", "7");
            put("14", "2");
            put("15", "14");
        }});
    }};

    public static Map<String, Map<String, String>> sBox5 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "2");
            put("1", "12");
            put("2", "4");
            put("3", "1");
            put("4", "7");
            put("5", "10");
            put("6", "11");
            put("7", "6");
            put("8", "8");
            put("9", "5");
            put("10", "3");
            put("11", "15");
            put("12", "13");
            put("13", "0");
            put("14", "14");
            put("15", "9");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "14");
            put("1", "11");
            put("2", "2");
            put("3", "12");
            put("4", "4");
            put("5", "7");
            put("6", "13");
            put("7", "1");
            put("8", "5");
            put("9", "0");
            put("10", "15");
            put("11", "10");
            put("12", "3");
            put("13", "9");
            put("14", "8");
            put("15", "6");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "4");
            put("1", "2");
            put("2", "1");
            put("3", "11");
            put("4", "10");
            put("5", "13");
            put("6", "7");
            put("7", "8");
            put("8", "15");
            put("9", "9");
            put("10", "12");
            put("11", "5");
            put("12", "6");
            put("13", "3");
            put("14", "0");
            put("15", "14");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "15");
            put("1", "3");
            put("2", "0");
            put("3", "6");
            put("4", "10");
            put("5", "1");
            put("6", "13");
            put("7", "8");
            put("8", "9");
            put("9", "4");
            put("10", "5");
            put("11", "11");
            put("12", "12");
            put("13", "7");
            put("14", "2");
            put("15", "14");
        }});
    }};

    public static Map<String, Map<String, String>> sBox6 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "12");
            put("1", "1");
            put("2", "10");
            put("3", "15");
            put("4", "9");
            put("5", "2");
            put("6", "6");
            put("7", "8");
            put("8", "0");
            put("9", "13");
            put("10", "3");
            put("11", "4");
            put("12", "14");
            put("13", "7");
            put("14", "5");
            put("15", "11");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "10");
            put("1", "15");
            put("2", "4");
            put("3", "2");
            put("4", "7");
            put("5", "12");
            put("6", "9");
            put("7", "5");
            put("8", "6");
            put("9", "1");
            put("10", "13");
            put("11", "14");
            put("12", "0");
            put("13", "11");
            put("14", "3");
            put("15", "8");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "9");
            put("1", "14");
            put("2", "15");
            put("3", "5");
            put("4", "2");
            put("5", "8");
            put("6", "12");
            put("7", "3");
            put("8", "7");
            put("9", "0");
            put("10", "4");
            put("11", "10");
            put("12", "1");
            put("13", "13");
            put("14", "11");
            put("15", "6");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "4");
            put("1", "3");
            put("2", "2");
            put("3", "12");
            put("4", "9");
            put("5", "5");
            put("6", "15");
            put("7", "10");
            put("8", "11");
            put("9", "14");
            put("10", "1");
            put("11", "7");
            put("12", "6");
            put("13", "0");
            put("14", "8");
            put("15", "13");
        }});
    }};

    public static Map<String, Map<String, String>> sBox7 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "4");
            put("1", "11");
            put("2", "2");
            put("3", "14");
            put("4", "15");
            put("5", "0");
            put("6", "8");
            put("7", "13");
            put("8", "3");
            put("9", "12");
            put("10", "9");
            put("11", "7");
            put("12", "5");
            put("13", "10");
            put("14", "6");
            put("15", "1");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "13");
            put("1", "0");
            put("2", "11");
            put("3", "7");
            put("4", "4");
            put("5", "9");
            put("6", "1");
            put("7", "10");
            put("8", "14");
            put("9", "3");
            put("10", "5");
            put("11", "12");
            put("12", "2");
            put("13", "15");
            put("14", "8");
            put("15", "6");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "1");
            put("1", "4");
            put("2", "11");
            put("3", "13");
            put("4", "12");
            put("5", "3");
            put("6", "7");
            put("7", "14");
            put("8", "10");
            put("9", "15");
            put("10", "6");
            put("11", "8");
            put("12", "0");
            put("13", "5");
            put("14", "9");
            put("15", "2");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "6");
            put("1", "11");
            put("2", "13");
            put("3", "8");
            put("4", "1");
            put("5", "4");
            put("6", "10");
            put("7", "7");
            put("8", "9");
            put("9", "5");
            put("10", "0");
            put("11", "15");
            put("12", "14");
            put("13", "2");
            put("14", "3");
            put("15", "12");
        }});
    }};
            

    public static Map<String, Map<String, String>> sBox8 = new HashMap<String, Map<String, String>>() {{
        put("0", new HashMap<String, String>(){{
            put("0", "13");
            put("1", "2");
            put("2", "8");
            put("3", "4");
            put("4", "6");
            put("5", "15");
            put("6", "11");
            put("7", "1");
            put("8", "10");
            put("9", "9");
            put("10", "3");
            put("11", "14");
            put("12", "5");
            put("13", "0");
            put("14", "12");
            put("15", "7");
        }});
        put("1", new HashMap<String, String>(){{
            put("0", "1");
            put("1", "15");
            put("2", "13");
            put("3", "8");
            put("4", "10");
            put("5", "3");
            put("6", "7");
            put("7", "4");
            put("8", "12");
            put("9", "5");
            put("10", "6");
            put("11", "11");
            put("12", "0");
            put("13", "14");
            put("14", "9");
            put("15", "2");
        }});
        put("2", new HashMap<String, String>(){{
            put("0", "7");
            put("1", "11");
            put("2", "4");
            put("3", "1");
            put("4", "9");
            put("5", "12");
            put("6", "14");
            put("7", "2");
            put("8", "0");
            put("9", "6");
            put("10", "10");
            put("11", "13");
            put("12", "15");
            put("13", "3");
            put("14", "5");
            put("15", "8");
        }});
        put("3", new HashMap<String, String>(){{
            put("0", "2");
            put("1", "1");
            put("2", "14");
            put("3", "7");
            put("4", "4");
            put("5", "10");
            put("6", "8");
            put("7", "13");
            put("8", "15");
            put("9", "12");
            put("10", "9");
            put("11", "0");
            put("12", "3");
            put("13", "5");
            put("14", "6");
            put("15", "11");
        }});
    }};
    // Sboxes take 6 bits as parameter
    // the outer two bits represent the row and the inner 4 bits represent the column
    
}
